BiocManager::install("clusterProfiler", force = TRUE)
BiocManager::install("pathview")
BiocManager::install("enrichplot")
install.packages("AnnotationDbi")
install.packages("ggridges")
BiocManager::install("fgsea", force = TRUE)


#rm(list = ls())
organism = "org.Dm.eg.db"
library(org.Dm.eg.db)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(fgsea)
library(ggridges)





###################GSEA##############

# reading in data from deseq2
df = read.csv("drosphila_example_de.csv", header=TRUE)

# This line extracts the "log2FoldChange" column from the data frame df 
#and assigns it to a vector called original_gene_list This vector contains the log2 fold change values
#which typically represent the changes in gene expression between conditions
original_gene_list <- df$log2FoldChange


#This line sets the gene names or identifiers (found in the "X" column of the data frame df) 
#as the names of the original_gene_list vector. 
#This step is essential because gene names will be used for further analysis and plotting
names(original_gene_list) <- df$X


# remove any NA values 
gene_list<-na.omit(original_gene_list)







# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)

gse <- gseGO(geneList=gene_list,
             ont ="ALL",
             keyType = "ENSEMBL",
             minGSSize = 3,
             maxGSSize = 800,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "none")

original_gene_list2 <- as.list(original_gene_list)



fgsea_result <- fgseaMultilevel(pathways = original_gene_list2,
                                stats = gene_list,
                                eps = 1e-10,
                                scoreType = c("std", "pos", "neg"),
                                nproc = 0,
                                gseaParam = 1,
                                minSize = 3,
                                BPPARAM = NULL,
                                nPermSimple	= 1000,
                                absEps = NULL,
                                maxSize = 800)



require(DOSE)

dotplot(gse, showCategory=10, split=".sign") + facet_grid(.~.sign)


#Enrichment map organizes enriched terms into a network with edges connecting overlapping gene sets. In this way, mutually overlapping gene sets are tend to cluster together, 
#making it easy to identify functional modules
x2<- pairwise_termsim(gse)
emapplot(x2,showCategory =10)

# The cnetplot depicts the linkages of genes and biological concepts (e.g. GO terms or KEGG pathways) as a network 
#(helpful to see which genes are involved in enriched pathways and genes that may belong to multiple annotation categories)
cnetplot(gse, categorySize="pvalue", color.params = list(foldChange = gene_list), showCategory = 3,max.overlaps =2000000)


#Grouped by gene set, density plots are generated by using the frequency of fold change values per gene within each set. 
#Helpful to interpret up/down-regulated pathways
ridgeplot(gse) + labs(x = "enrichment distribution")

